### ISSUE TITLE
"Parameter not valid" exception randomly occuring

### ISSUE THREAD

**Issue by Loydik** [MathewSachin/Screna#12]
Hi, I am trying to use your framework for recording automated tests. Unfortunately recording video is not stable - running and recording the same test produced different outcomes at random. For example, sometime the recording was complete, and at other times the video was only 10 seconds long (should be 30)

I've debugged your source code an the problem seems to be at:

Recorder.Record(), which catches exception "Parameter not valid" and stops the recording abruptly. Here is stacktrace:

   at System.Drawing.Graphics.GetHdc()
   at System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize, CopyPixelOperation copyPixelOperation)
   at System.Drawing.Graphics.CopyFromScreen(Point upperLeftSource, Point upperLeftDestination, Size blockRegionSize, CopyPixelOperation copyPixelOperation)
   at Screna.ScreenShot.CaptureRegionManaged(Rectangle Region, Boolean IncludeCursor) in C:\Users\SG0222640\Desktop\Sample Projects\Screna-master\Screna-master\src\Core\ScreenShot.cs:line 277
   at Screna.ScreenShot.Capture(Rectangle Region, Boolean IncludeCursor, Boolean Managed) in C:\Users\SG0222640\Desktop\Sample Projects\Screna-master\Screna-master\src\Core\ScreenShot.cs:line 297
   at Screna.ScreenShot.Capture(Screen Screen, Boolean IncludeCursor, Boolean Managed) in C:\Users\SG0222640\Desktop\Sample Projects\Screna-master\Screna-master\src\Core\ScreenShot.cs:line 47
   at Screna.ScreenProvider.OnCapture(Graphics g) in C:\Users\SG0222640\Desktop\Sample Projects\Screna-master\Screna-master\src\Core\ImageProviders\ScreenProvider.cs:line 32
   at Screna.ImageProviderBase.Capture() in C:\Users\SG0222640\Desktop\Sample Projects\Screna-master\Screna-master\src\Core\ImageProviders\ImageProviderBase.cs:line 36
   at Screna.Recorder.Record() in C:\Users\SG0222640\Desktop\Sample Projects\Screna-master\Screna-master\src\Core\Recorder\Recorder.cs:line 148

This exception is caught here:

catch (Exception e)
{
                Stop();
                RaiseRecordingStopped(e);
}

And the recording is stopped. Could you please look into it?

I am using AviCodec.X264

**Comment by MathewSachin** [comment]
Please check the fixing-12 branch.

**Comment by Loydik** [comment]
Thanks, Mathew, I will verify it on Monday at work and will let you know

**Comment by MathewSachin** [comment]
OK

**Comment by Loydik** [comment]
It looks like the problem has disappeared. Thank you!

**Comment by MathewSachin** [comment]
That means I can merge the `fixing-12` branch?

**Comment by Loydik** [comment]
I think yes, and you can release a new version, because it was a major issue - made Screna completely unusable for us. Thank you for your effort!

**Comment by kroky-cs** [comment]
When will you release it on nuget

**Comment by MathewSachin** [comment]
I have already released this on NuGet: v0.5.2

**Comment by kroky-cs** [comment]
The fix is not working and the issue is still exist also RaiseRecordingStopped(e) doesn't call _recorder.RecordingStopped when this exception is occurred.
There is another strange issue I found and I guess this is the problem, the WriteFrameAsync Method doesn't write in the file until the recorder stopped manually, I mean the outout file is zero byte until the recording finished which lets the app take more much memory than it need until this error happens because of out of memory

**Comment by Loydik** [comment]
I've also observed a similar problem before, but was not able to reproduce it after this fix. 
However this may be linked with issue - [Screna memory leaks + Video speed too fast #14](https://github.com/MathewSachin/Screna/issues/14)

**Comment by kroky-cs** [comment]
This is same issue but the update didn't solve it and I found the the image is fixed after some time in the recording

**Comment by kroky-cs** [comment]
I check the application on another machine and it is working, I don't know why it is not working on my machine, probably it is caching issue

Thanks Mathew & Loydik for your help

**Comment by kroky-cs** [comment]
There is another problem that I found WriteFrameAsync throw out of memory exception in Bitmap.LockBits

**Comment by kroky-cs** [comment]
I solved this issue by re-implementing WriteFrameAsync by this code
` /// <summary>
        /// Asynchronously writes an Image frame.
        /// </summary>
        /// <param name="Image">The Image frame to write.</param>
        /// <returns>The Task Object.</returns>
        public Task WriteFrameAsync(Bitmap Image)
        {
            return Task.Run(async () =>
            {
                unsafe
                {
                    var bits = Image.LockBits(new Rectangle(Point.Empty, Image.Size), ImageLockMode.ReadOnly, PixelFormat.Format32bppRgb);
                    //Marshal.Copy(bits.Scan0, _videoBuffer, 0, _videoBuffer.Length);

                    byte* ImageStart = (byte*)bits.Scan0;
                    Parallel.For(0, _videoBuffer.Length, y =>
                    {
                        _videoBuffer[y] = ImageStart[y];
                    });

                    Image.UnlockBits(bits);
                    Image.Dispose();
                }
                await _videoStream.WriteFrameAsync(true, _videoBuffer, 0, _videoBuffer.Length);
            });
        }`

**Comment by MathewSachin** [comment]
I think the problem was that the Image was not being disposed which was leading to OutOfMemory error. I would prefer that the image is disposed from the recorder. Wait patiently for the next commit. Thank You.

**Comment by MathewSachin** [comment]
@kroky-cs please check the latest commit.

**Comment by kroky-cs** [comment]
Hi @MathewSachin the same problem.
your solution will be the best working solution if you implement it not in recorder but before this line
`await _videoStream.WriteFrameAsync(true, _videoBuffer, 0, _videoBuffer.Length);`
in the public Task WriteFrameAsync(Bitmap Image) in the AviWriter class

`public Task WriteFrameAsync(Bitmap Image)
        {
            return Task.Run(async () =>
            {
                var bits = Image.LockBits(new Rectangle(Point.Empty, Image.Size), ImageLockMode.ReadOnly, PixelFormat.Format32bppRgb);
                Marshal.Copy(bits.Scan0, _videoBuffer, 0, _videoBuffer.Length);
                Image.UnlockBits(bits);
                Image.Dispose();

                await _videoStream.WriteFrameAsync(true, _videoBuffer, 0, _videoBuffer.Length);
            });
}`

**Comment by MathewSachin** [comment]
Check the latest commit. Did exactly what you said.

**Comment by kroky-cs** [comment]
@MathewSachin Thanks alot, you are my man
If you have time can you prepare nuget version?

**Comment by MathewSachin** [comment]
I'm sorry, you'll have to wait for 3 hrs. As soon as I get home I would do that

**Comment by kroky-cs** [comment]
no problem, I am not in a hurry.

**Comment by MathewSachin** [comment]
Released v0.5.3

**Comment by kroky-cs** [comment]
Thanks @MathewSachin

---

Thanks & Regards

[image: Venta Apps] <http://www.ventaapps.com/>

Karim Abd El-AAl / Co-founder
kimo27eg@gmail.com / +201000958778

Venta Apps
info@ventaapps.com / +2035750078
6 Zo El Fakar St. Loran, Alexandria, Egypt
http://www.ventaapps.com

[image: Facebook]  <https://www.facebook.com/krokys>[image: Twitter]
<https://twitter.com/Kroky_cs>[image: Google Plus]
<https://plus.google.com/+KarimAbdElAAl>[image: Linkedin]
<https://www.linkedin.com/in/kroky>[image: skype]

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Venta Apps is not
responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.
